# Talky Configuration

# Hotkey to trigger recording
hotkey: "ctrl+shift+space"

# Recording duration in seconds
recording_duration_sec: 5.0

# OpenAI API settings
openai:
  model: "whisper-1"
  
# Audio recording settings
audio:
  sample_rate: 16000
  channels: 1
  bit_depth: 16  # Valid values: 8, 16, 24, 32
