
api:
  # URL for the speech-to-text API
  # To use a local model, set this to the address of the model such as "localhost:8080"
  url: "https://api.openai.com/v1/audio/transcriptions"
  # Temperature parameter for the API
  temperature: 0.0
  # Temperature increment parameter for the API
  temperature_inc: 0.2